-- Tabla Customer
CREATE TABLE customer
(
    dni         VARCHAR2(9)     NOT NULL,
    name        VARCHAR2(25)    NOT NULL,
    surname     VARCHAR2(25)    NOT NULL,
    email       VARCHAR2(50)    NOT NULL,
    phonenumber VARCHAR2(15)    NOT NULL,
    CONSTRAINT pk_customer PRIMARY KEY (dni)
);

-- Tabla Room
CREATE TABLE room
(
    roomNumber INT              GENERATED BY DEFAULT AS IDENTITY,
    roomType   CHAR(1)          NOT NULL,
    price      NUMBER(8,2)      NOT NULL,
    status     CHAR(1)          DEFAULT 'D' NOT NULL,
    CONSTRAINT pk_room PRIMARY KEY (roomNumber)
);